version: '3.8'

services:
  app:
    image: sapiens-app-backend
    container_name: sapiens_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "1.0"       # Limite de CPU, 1.0 significa 1 CPU
          memory: 1024M      # Limite de memória
        reservations:
          cpus: "0.5"       # Reserva de CPU, 0.5 significa meio CPU
          memory: 512M      # Reserva de memória